---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  labels:
    app: example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      name: example-app
      labels:
        app: example-app
    spec:
      initContainers:
        - name: init
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z -w1 $REDIS_HOST $REDIS_PORT; do echo "Waiting for Redis to be ready..."; sleep 2; done; echo "Redis is ready!"']
          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
      containers:
        - name: example-app
          image: myapp:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"

---

apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  type: NodePort
  selector:
    app: example-app
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30007
